"""Base classes shared by all model types."""

from typing import ClassVar, Generic, List, Type, TypeVar

from marshmallow import Schema

from tju.exceptions import DataError


class Result:
    """Base class for a single typed result item.  Each subclass carries a
    marshmallow ``Schema`` class attribute generated by ``marshmallow-dataclass``."""

    Schema: ClassVar[Type["Schema"]] = Schema


T_Result = TypeVar("T_Result", bound=Result)


class QueryResult(Generic[T_Result]): ...


class Results(List[T_Result]):
    """Typed list of :class:`Result` items.  Subclasses set ``_item`` to the
    concrete dataclass and call :meth:`load` to deserialise a list of dicts."""

    _item: Type[T_Result]

    def __init__(self):
        super().__init__()

    def load(self, data: list):
        """Deserialise *data* (list of dicts) into typed items and extend this list."""
        schema = self._item.Schema(many=True)
        results = schema.load(data)
        if results is None:
            raise DataError("Failed to load data")
        self.extend(results)
